name: Hermes Client Build

on:
  workflow_dispatch:

jobs:
  build-armbian:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Checkout Armbian build
        uses: actions/checkout@v4
        with:
          repository: armbian/build
          path: build

      - name: Check System Info
        run: |
          pwd
          ls -la

      - name: Install device-tree-compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y device-tree-compiler

      - name: Move Folder
        run: |
          cd build
          mv userpatches build

      - name: Generate DTB
        run: |
          # 把 extracted.dts 放在这里，生成同名 dtb
          dtc -I dts -O dtb -o build/arch/arm64/boot/dts/rockchip/rk3308-evb-dmic-pdm-v13.dtb \
              build/userpatches/extracted.dts || echo "No custom DTB provided"

      - name: Build Armbian image
        run: |
          cd build
          ./compile.sh \
            BOARD=rk3308 \
            BRANCH=current \
            RELEASE=bookworm \
            BUILD_MINIMAL=yes \
            BUILD_DESKTOP=no \
            COMPRESS_OUTPUTIMAGE=sha,img 

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: armbian-rk3308-e1
          path: output/images/*.img