name: Hermes Client Build

on:
  workflow_dispatch:

jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Armbian Build
        run: git clone https://github.com/armbian/build

      - name: Install device-tree-compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y device-tree-compiler

      - name: Build Armbian image
        run: |
          cd build
          # Create required directory structure
          mkdir -p arch/arm64/boot/dts/rockchip
          
          # Check for custom DTS file and build DTB
          if [ -f ../userpatches/extracted.dts ]; then
            echo "Building custom DTB from extracted.dts"
            dtc -I dts -O dtb -o arch/arm64/boot/dts/rockchip/sogou_e1.dtb \
                ../userpatches/extracted.dts || { echo "DTB build failed"; exit 1; }
          else
            echo "No custom DTS file found, using default configuration"
          fi
          
          # Run Armbian compile with proper parameters
          ./compile.sh \
            BOARD=sogou_e1 \
            BRANCH=current \
            RELEASE=bookworm \
            BUILD_MINIMAL=yes \
            BUILD_DESKTOP=no \
            COMPRESS_OUTPUTIMAGE=sha,img \
            KERNEL_COMPILER=clang \
            KERNEL_CONFIGURE=no

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: armbian-rk3308-e1
          path: build/output/images/*.img