name: Hermes Client Build

on:
  workflow_dispatch:

jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Armbian Build
        run: git clone https://github.com/armbian/build

      - name: Install device-tree-compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y device-tree-compiler

      - name: Build Armbian image
        run: |
          cd build
          
          # 创建板级配置目录
          mkdir -p ../userpatches/config/board/sogou_e1
          
          # 创建板级配置文件
          cat > ../userpatches/config/board/sogou_e1/sogou_e1.conf << 'EOL'
          # Sogou E1 board configuration
          BOARD_NAME="Sogou E1"
          BOARDFAMILY="rockchip64"
          BOOTCONFIG="rk3308-evb_defconfig"
          KERNEL_TARGET="current"
          BOOT_FDT_FILE="rockchip/sogou_e1.dtb"
          EOL
          
          # 创建设备树输出目录
          mkdir -p arch/arm64/boot/dts/rockchip
          
          # 检查DTS源文件并生成DTB
          if [ -f ../userpatches/extracted.dts ]; then
            cp ../userpatches/extracted.dts ../userpatches/config/board/sogou_e1/sogou_e1.dts
            
            cd ../userpatches/config/board/sogou_e1
            dtc -I dts -O dtb -o ../../../../../../build/arch/arm64/boot/dts/rockchip/sogou_e1.dtb \
                sogou_e1.dts || { echo "设备树编译失败"; exit 1; }
            cd ../../../../../../build
          else
            echo "未找到DTS源文件，使用默认配置"
          fi
          
          # 执行Armbian编译
          ./compile.sh \
            BOARD=sogou_e1 \
            BRANCH=current \
            RELEASE=bookworm \
            BUILD_MINIMAL=yes \
            BUILD_DESKTOP=no \
            COMPRESS_OUTPUTIMAGE=sha,img \
            KERNEL_COMPILER=clang \
            KERNEL_CONFIGURE=no 

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: armbian-rk3308-e1
          path: build/output/images/*.img